
name: NodeChoclo.js CI

on:
  push:
    branches: [ main, todoinicio ]
  pull_request:
    branches: [ main, todoinicio ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci    
    - run: npm test
